# MySQL datasource configuration
spring:
  servlet:
    multipart:
      max-file-size: 5MB  # Tamanho máximo de um único arquivo
      max-request-size: 20MB  # Tamanho máximo da requisição (todos os arquivos somados)
      enabled: true  # Habilita o suporte a multipart
  datasource:
    url: jdbc:mysql://localhost:3306/hotel?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
api:
  security:
    token:
      expiration: 1
      secret: ${JWT_SECRET:my-secret-key}
    refresh-token:
      expiration: 8
file:
  upload-dir: /uploads
springdoc:
  swagger-ui:
    tags-sorter: method
    operations-sorter: alpha